name: Setup
description: Setup
inputs:
  node_version:
    description: Node version to use
    required: true
  token:
    description: Token
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node.js 🔠
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ inputs.node_version }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}

    - name: Cache node modules 💸
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Dependencies 🪛
      shell: bash
      run: npm i
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
