name: Setup
description: Setup
inputs:
  node_version:
    description: Node version to use
    required: true
  token:
    description: Token
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node.js 🔠
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: ${{ inputs.node_version }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}

    - name: Cache node modules 💸
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Dependencies 🪛
      shell: bash
      run: npm i
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
