/** API paths for the Descope service Management APIs */
export default {
  user: {
    create: '/v1/mgmt/user/create',
    update: '/v1/mgmt/user/update',
    delete: '/v1/mgmt/user/delete',
    deleteAllTestUsers: '/v1/mgmt/user/test/delete/all',
    load: '/v1/mgmt/user',
    search: '/v1/mgmt/user/search',
    updateStatus: '/v1/mgmt/user/update/status',
    updateEmail: '/v1/mgmt/user/update/email',
    updatePhone: '/v1/mgmt/user/update/phone',
    updateDisplayName: '/v1/mgmt/user/update/name',
    updatePicture: '/v1/mgmt/user/update/picture',
    updateCustomAttribute: '/v1/mgmt/user/update/customAttribute',
    addRole: '/v1/mgmt/user/update/role/add',
    removeRole: '/v1/mgmt/user/update/role/remove',
    addTenant: '/v1/mgmt/user/update/tenant/add',
    removeTenant: '/v1/mgmt/user/update/tenant/remove',
    generateOTPForTest: '/v1/mgmt/tests/generate/otp',
    generateMagicLinkForTest: '/v1/mgmt/tests/generate/magiclink',
    generateEnchantedLinkForTest: '/v1/mgmt/tests/generate/enchantedlink',
  },
  accessKey: {
    create: '/v1/mgmt/accesskey/create',
    load: '/v1/mgmt/accesskey',
    search: '/v1/mgmt/accesskey/search',
    update: '/v1/mgmt/accesskey/update',
    deactivate: '/v1/mgmt/accesskey/deactivate',
    activate: '/v1/mgmt/accesskey/activate',
    delete: '/v1/mgmt/accesskey/delete',
  },
  tenant: {
    create: '/v1/mgmt/tenant/create',
    update: '/v1/mgmt/tenant/update',
    delete: '/v1/mgmt/tenant/delete',
    loadAll: '/v1/mgmt/tenant/all',
  },
  sso: {
    configure: '/v1/mgmt/sso/settings',
    metadata: '/v1/mgmt/sso/metadata',
    mapping: '/v1/mgmt/sso/mapping',
  },
  jwt: {
    update: '/v1/mgmt/jwt/update',
  },
  permission: {
    create: '/v1/mgmt/permission/create',
    update: '/v1/mgmt/permission/update',
    delete: '/v1/mgmt/permission/delete',
    loadAll: '/v1/mgmt/permission/all',
  },
  role: {
    create: '/v1/mgmt/role/create',
    update: '/v1/mgmt/role/update',
    delete: '/v1/mgmt/role/delete',
    loadAll: '/v1/mgmt/role/all',
  },
  flow: {
    export: '/v1/mgmt/flow/export',
    import: '/v1/mgmt/flow/import',
  },
  theme: {
    export: '/v1/mgmt/theme/export',
    import: '/v1/mgmt/theme/import',
  },
  group: {
    loadAllGroups: '/v1/mgmt/group/all',
    loadAllGroupsForMember: '/v1/mgmt/group/member/all',
    loadAllGroupMembers: '/v1/mgmt/group/members',
  },
};
